### ISSUE TITLE
change config file format?

### ISSUE THREAD

**Issue by bheavner** [ini-bdds/minid#29]
Can we tweak the config file format? If the first line were `general:` instead of `[general]`, then the R `config` package would read it as YAML, and it would be easier to work with. I can likely parse the current syntax in R if needed, but the package makes it easier. I'd rather use the same config file format for R and python if it's an easy change in python (or if python can use both).

as an example: this works for me in R with the config package:
```
general:
  minid_server: http://minid.bd2k.org/minid
  user: <Name>
  email: <Email>
  orcid: <optional Orcid>
  code: <Code>
```

**Comment by bheavner** [comment]
This may be an issue with R YAML stuff... will follow up after more reading...

**Comment by bheavner** [comment]
Never mind, I can read it with `configr` instead of `config`. All's well, no changes needed.

**Comment by bheavner** [comment]
Actually, I take that back. The config file seems to be something in-between other formats. Could it be an ini file (using `=` instead of : for key/value separation) or YAML file (not using the `[]` section headers, I think?)?

If we use one of the formats described here: https://life2cloud.com/en/2017/07/configuration-filetypes/ it'll be easier to use from R or python, I think.

**Comment by bheavner** [comment]
The easiest thing for me to use in R at the moment would be a yaml using a default configuration, like this:
```
default:
  minid_server: http://minid.bd2k.org/minid
  user: <Name>
  email: <Email>
  orcid: <optional Orcid>
  code: <Code>
```
